name: Changelog Validation

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  validate-changelog:
    name: Validate changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Validate changelogs
        uses: Kong/gateway-changelog@main
        with:
          files: changelog/unreleased/*/*.yml
